<table class="bgtop">
	<tr><td>
		<a href="http://rule34.paheal.net"><img alt="logo" src="http://rule34.paheal.net/themes/rule34v2/rule34_logo_top.png"/></a>
			</td></tr>
</table>

<form action='/post/list' method='GET' id="barbot">
	<input name='search' size="45" type='text' placeholder='Search' autocomplete='off'/>
	<input type='submit' value='Find' id="submit"/>
</form>

<br>
<div id="menuh-container">
<div id="menuh">

	<ul>
		<li><a href="http://rule34.paheal.net/post/list" class="top_parent">Main</a>
		<ul>
			<li><a href="http://rule34.paheal.net/post/list" class="sub_option">Home page</a></li>
			<li><a href="http://rule34.paheal.net/comment/list" class="sub_option">Comments</a></li>
			<li><a href="http://rule34.paheal.net/tags" class="sub_option">Tags</a></li>
			<li><a href="http://rule34.paheal.net/upload" class="sub_option">Upload</a></li>
			<li><a href="http://rule34.paheal.net/wiki/rules" class="sub_option">Site rules</a></li>
            <li><a href="http://rule34.paheal.net/wiki/faq" class="sub_option">F.A.Q.</a></li>
			<li><a href="http://rule34.paheal.net/wiki/staff" class="sub_option">Staff</a></li>
			<li><a href="#" class="parent">Contact</a>
			<ul>
				<li><a href="mailto:staff@paheal.net" class="sub_option">Staff</a></li>
				<li><a href="mailto:wiiaboo@paheal.net" class="sub_option">Founder</a></li>
				<li><a href="mailto:webmaster@shishnet.org" class="sub_option">Programmer</a></li>
			</ul>
			</li>
		</ul>
		</li>
	</ul>
    
    <ul>	
		<li><a href="#" class="top_parent">Sites</a>
		<ul>
			<li><a href="http://rule34.paheal.net/" class="sub_option">Rule #34</a></li>
			<li><a href="http://rule63.paheal.net/" class="sub_option">Rule #63</a></li>
			<li><a href="http://cosplay.paheal.net/" class="sub_option">Cosplay</a></li>
			<li><a href="http://rule34c.paheal.net/" class="sub_option">Rule #34c</a></li>
			<!--<li><a href="http://rule35.paheal.net/" class="sub_option">Rule #35</a></li>-->
		</ul>
		</li>
	</ul>
    
	<ul>
		<li><a href="#" class="top_parent">Community</a>
		<ul>
			<!--<li><a href="http://forum.paheal.net" class="sub_option">Forum</a></li>-->

			<li><a href="http://rule34.paheal.net/wiki/friends" class="parent">Friends of paheal</a>

			<li><a href="http://rule34.paheal.net/wiki/DNP" class="parent">DNP List</a>

			<li><a href="#" class="parent">Chat</a>
			<ul>
				<li><a href="irc://irc.rizon.net/rule34" class="sub_option">irc.rizon.net/rule34</a></li>
				<li><a href="http://rule34.paheal.net/themes/rule34/irc/index.html" target="new" class="sub_option">Web Chat</a></li>
			</ul>
			</li>
		</ul>
		</li>
	</ul>
	
	<ul>
		<li><a class="menu top_parent" href="http://rule34.paheal.net/wiki/Notes">ANNOUNCEMENTS</a></li>
	</ul>
	
</div>
</div>
